<h1  property="schema:name">Terms of Use</h1>  </div>

  
  </div>
<div class="panel-separator"></div><div class="panel-pane pane-node-body"  >
  
      
  
  <div class="pane-content">
    
  <div class="field field-name-body field-type-text-with-summary field-label-hidden ">
   
<h5>1. GENERAL TERMS.</h5>
<p>These Terms of Use and Additional Terms and Conditions (“Agreement)” set forth the terms and conditions that apply to your access and use of the BladeGuyRoberto (BGR) Finance Website and mobile App (“BGR Services”) as owned and operated by BGR Inc., its subsidiaries and/or affiliates, and mobile App (collectively "BGR Services") as owned and operated by BGR, Inc., formerly known as Finance Website, its subsidiaries, affiliates are collectively “BGR Finance”. For licensing inquiries, please contact us.</p>
<p>As used in this Agreement, the term "Sites" includes all websites, pages that are associated or within each website and all devices, applications or services that BGR operates or offers that link to this Agreement. By accepting electronically (for example, clicking “I Agree”), installing, accessing or using the Services, you agree to be bound by the terms and conditions of this Agreement Privacy and Security Policy, as they may be amended from time to time in the future (see “Modifications” below). If you do not agree to this Agreement, then you may not use the Services.</p>
<ul id="toc">
<li>Accepting the Terms</li>
<li>Privacy and your Personal Information</li>
<li>Description of the Services</li>
<li>Account Information from Third Party Sites</li>
<li>BGR Offers and Third-Party Links</li>
<li>Your Registration Information</li>
<li>Your Use of the Service</li>
<li>Use With Your Mobile Device</li>
<li>Online and Mobile Alerts</li>
<li>Rights You Grant to Us</li>
<li>BGR’s Intellectual Property Rights</li>
<li>Access and Interference</li>
<li>Rules for Posting</li>
<li>Social Media Sites</li>
<li>Disclaimer of Representations and Warranties</li>
<li>Not a Financial Planner, Broker or Tax Advisor</li>
<li>Limitations on BGR’s Liability</li>
<li>Your Indemnification of BGR</li>
<li>Ending your relationship with BGR</li>
<li>Modifications</li>
<li>Governing Law and Forum for Disputes</li>
<li>Miscellaneous</li>
<li>BGR QuickView</li>
<li>Credit Score Services</li>
<li>Bill Payment Services</li>
<li>Bill Processing Services</li>
<li>Apple Requirements</li>
</ul>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>1. Accepting the Terms</h5>
<p>By using the information, tools, features, software and functionality including content, updates and new releases provided by BGR of the “BGR Service or the Bill Pay Services provided by BGR Bills, you agree to be bound by this Agreement, whether you are a “Visitor” (which means that you simply browse the BGR.com website), a “Member” (which means that you have registered with BGR.com) or a “Customer” (which means that you have registered or used the Bill Payment Service or Biller Processing Services.) The term “you” or “User” refers to a Visitor, Member or Customer. The term “we” refers to BGR. If you wish to become a Member, communicate with other Members, become a Customer of the Bill Pay Services, or make use of the Services, you must read this Agreement and indicate your acceptance during the registration process.</p>
<p>You may not use the BGR Service or the Bill Pay Services and you may not accept this Agreement if you are not are not at least 18 years of age and, in any event, of a legal age to form a binding contract with BGR.</p>
<p>If you accept this Agreement, you represent that you have the capacity to be bound by it or if you are acting on behalf of a company or entity that you have the authority to bind such entity. Before you continue, you should print or save a local copy of this Agreement for your records.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>2. Privacy and your Personal Information</h5>
<p>You can view <a href="/privacy_policy">BGR Privacy Policy</a> here and on the Site for the Services. You agree to the applicable BGR Privacy Statement, and any changes published by BGR. You agree that BGR may use and maintain your data according to the BGR’s Privacy Statement, as part of the Services. You give BGR permission to combine information you enter or upload for the Services with that of other users of the Services and/or other BGR services. For example, this means that BGR may use your and other users’ non-identifiable, aggregated data to improve the Services or to design promotions. BGR may access or store personal information in multiple countries, including countries outside of your own country to the extent permitted by applicable law.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>3. Description of the Services</h5>
<p>The BGR Service is a personal finance information management service that allows you to consolidate and track your financial information. The BGR Service is provided to you by BGR without charge (it is free) and is meant to provide you with your information to allow you to organize and manage your finances.</p>
<p>The BGR Service may also include a service that provides your one-bureau credit summary, credit score and monitoring alerts (“Credit Score Service”). You may have the option to obtain this Credit Score Service for free or elect to purchase an upgraded version of this service that provides you information from multiple credit bureaus (“BGR
 Credit Monitoring”).</p>
<p>The Bill Pay Services offers various tools and functions through the Sites including a personal information management service that allows you to consolidate and track certain personal information and a fee based bill payment service that allows you to make payments to third parties as further described in Section 25 below.</p>
<p>The Services may also present you information relating to third party products or services (“BGR Offers”), as well as provide you general tips, recommendations and educational material.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>4. Account Information from Third Party Sites</h5>
<p>Users may direct BGR to retrieve their own information maintained online by third-parties with which they have customer relationships, maintain accounts or engage in financial transactions (“Account Information”). BGR works with one or more online service providers to access this Account Information. BGR makes no effort to review the Account Information for any purpose, including but not limited to accuracy, legality or non-infringement. BGR is not responsible for the products and services offered by or on third-party sites.</p>
<p>BGR cannot always foresee or anticipate technical or other difficulties which may result in failure to obtain data or loss of data, personalization settings or other service interruptions. BGR cannot assume responsibility for the timeliness, accuracy, deletion, non-delivery or failure to store any user data, communications or personalization settings. For example, when displayed through the Services, Account Information is only as fresh as the time shown, which reflects when the information is obtained from such sites. Such information may be more up-to-date when obtained directly from the relevant sites. You can refresh your Account Information through the Services, in the manner prescribed in the associated instructions.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>5. BGR Offers and Third-Party Links</h5>
<p>Some parts of the Services are supported by sponsored links from advertisers and display BGR Offers that may be custom matched to you based on information stored in the Services, queries made through the Services or other information. We will always disclose when a particular BGR Offer is sponsored.</p>
<p>In connection with BGR Offers, the Services will provide links to other web sites belonging to BGR advertisers and other third parties. BGR does not endorse, warrant or guarantee the products or services available through the BGR Offers (or any other third-party products or services advertised on or linked from our site), whether or not sponsored, and BGR is not an agent or broker or otherwise responsible for the activities or policies of those web sites. BGR does not guarantee that the loan, investment, plan or other service terms, rates or rewards offered by any particular advertiser or other third party on the Sites are actually the terms that may be offered to you if you pursue the offer or that they are the best terms or lowest rates available in the market.</p>
<p>If you elect to use or purchase services from third parties, you are subject to their terms and conditions and privacy policy.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>6. Your Registration Information</h5>
<p>In order to allow you to use the Services, you will need to sign up for an account with BGR. We may verify your identity. You authorize us to make any inquiries we consider necessary to validate your identity. These inquiries may include asking you for further information, requiring you to provide your full address, your social security number and/or requiring you to take steps to confirm ownership of your email address or financial instruments, ordering a credit report, or verifying information you provide against third party databases or through other sources. If you do not provide this information or BGR cannot verify your identity, we can refuse to allow you to use the Services.</p>
<p>You agree and understand that you are responsible for maintaining the confidentiality of your password which, together with your LoginID e-mail address, allows you to access the Sites. That LoginID and password, together with any mobile number or other information you provide form your “Registration Information.” By providing us with your e-mail address, you agree to receive all required notices electronically, through the Services by displaying links to notices generally on the Site, to that e-mail address. It is your responsibility to update or change that address, as appropriate. Notices will be provided in HTML (or, if your system does not support HTML, in plain-text) in the text of the e-mail or through a link to the appropriate page on our site, accessible through any standard, commercially available internet browser.</p>
<p>If you become aware of any unauthorized use of your Registration or Account Information for the Services, you agree to notify BGR immediately at the email address - <a href="mailto:security@BGR.com">security@BGR.com</a>.</p>
<p>If you believe that your Registration or Account Information or device that you use to access the Bill Pay Services has been lost or stolen, that someone is using your account without your permission, or that an Unauthorized Transfer (as defined in Section 25.1 Bill Payment Service below) has occurred, you must notify BGR Bills immediately in order to minimize your possible losses.</p>
<p>The following is BGR’s contact information:</p>
<p>Telephone: 555-555-1234</p>
<p>Email: <a href="mailto:care@bills.bgr.com">care@bills.bgr.com</a></p>
<p>Address 1 The Drive The Great State of, CA 93401</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>7. Your Use of the Services</h5>
<p>Your right to access and use the Sites and the Services is personal to you and is not transferable by you to any other person or entity. You are only entitled to access and use the Sites and Services for lawful purposes. Accurate records enable BGR to provide the Services to you. You must provide true, accurate, current and complete information about your accounts maintained at other web sites, as requested in our “add account” setup forms, and you may not misrepresent your Registration and Account Information. In order for the Services to function effectively, you must also keep your Registration and Account Information up to date and accurate. If you do not do this, the accuracy and effectiveness of the Services will be affected. You represent that you are a legal owner of, and that you are authorized to provide us with, all Registration and Account Information and other information necessary to facilitate your use of the Services.</p>
<p>Your access and use of. Services may be interrupted from time to time for any of several reasons, including, without limitation, the malfunction of equipment, periodic updating, maintenance or repair of the Services or other actions that BGR, in its sole discretion, may elect to take. In no event will BGR be liable to any party for any loss, cost, or damage that results from any scheduled or unscheduled downtime.</p>
<p>Your sole and exclusive remedy for any failure or non-performance of the Services, including any associated software or other materials supplied in connection with such services, shall be for BGR to use commercially reasonable efforts to effectuate an adjustment or repair of the applicable service.</p>
<p>From time to time, BGR may include new and/or updated pre-release features and trial use (“Sneak Preview” features) in Services for your use and which permit you to provide feedback. You understand and agree that your use of Sneak Preview features is voluntary and BGR is not obligated to provide you with any Sneak Preview features. Furthermore, if you decide to use the Sneak Preview features you agree to abide by any rules or restrictions BGR may place on them. You understand that once you use the Sneak Preview features, you may be unable to revert back to the earlier version of the same or similar feature. Additionally, if such reversion is possible, you may not be able to return or restore data created within the Sneak Preview feature back to the earlier version. The Sneak Preview features are provided on an “as is” basis and may contain errors or inaccuracies that could cause failures, corruption or loss of data and/or information from any connected device. You acknowledge and agree that all use of the Sneak Preview features is at your sole risk.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>8. Use With Your Mobile Device</h5>
<p>Use of these Services may be available through a compatible mobile device, Internet and/or network access and may require software. You agree that you are solely responsible for these requirements, including any applicable changes, updates and fees as well as the terms of your agreement with your mobile device and telecommunications provider. BGR MAKES NO WARRANTIES OR REPRESENTATIONS OF ANY KIND, EXPRESS, STATUTORY OR IMPLIED AS TO: (i) THE AVAILABILITY OF TELECOMMUNICATION SERVICES FROM YOUR PROVIDER AND ACCESS TO THE SERVICES AT ANY TIME OR FROM ANY LOCATION; (ii) ANY LOSS, DAMAGE, OR OTHER SECURITY INTRUSION OF THE TELECOMMUNICATION SERVICES; AND (iii) ANY DISCLOSURE OF INFORMATION TO THIRD PARTIES OR FAILURE TO TRANSMIT ANY DATA, COMMUNICATIONS OR SETTINGS CONNECTED WITH THE SERVICES.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>9. Online and Mobile Alerts</h5>
<p>BGR may from time to time provide automatic alerts and voluntary account-related alerts. Automatic alerts may be sent to you following certain changes to your account or information, such as a change in your Registration Information.</p>
<p>Voluntary account alerts may be turned on by default as part of the Services. They may then be customized, deactivated or reactivated by you. These alerts allow you to choose alert messages for your accounts. BGR may add new alerts from time to time, or cease to provide certain alerts at any time upon its sole discretion. Each alert has different options available, and you may be asked to select from among these options upon activation of your alerts service.</p>
<p>You understand and agree that any alerts provided to you through the Services may be delayed or prevented by a variety of factors. BGR may make commercially reasonable efforts to provide alerts in a timely manner with accurate information, but cannot guarantee the delivery, timeliness, or accuracy of the content of any alert. BGR shall not be liable for any delays, failure to deliver, or misdirected delivery of any alert; for any errors in the content of an alert; or for any actions taken or not taken by you or any third party in reliance on an alert.</p>
<p>Electronic alerts will be sent to the email address you have provided as your primary email address for the Services. If your email address or your mobile device’s email address changes, you are responsible for informing us of that change. You can also choose to have alerts sent to a mobile device that accepts text messages. Changes to your email address or mobile number will apply to all of your alerts.</p>
<p>Because alerts are not encrypted, we will never include your passcode. However, alerts may include your Login ID and some information about your accounts. Depending upon which alerts you select, information such as an account balance or the due date for your credit card payment may be included. Anyone with access to your email will be able to view the content of these alerts. At any time you may disable future alerts.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>10. Rights You Grant to Us</h5>
<p>By submitting information, data, passwords, usernames, PINs, other log-in information, materials and other content to BGR through the Services, you are licensing that content to BGR for the purpose of providing the Services. BGR may use and store the content in accordance with this Agreement and our Privacy Statement. You represent that you are entitled to submit it to BGR for use for this purpose, without any obligation by BGR to pay any fees or be subject to any restrictions or limitations. By using the Services, you expressly authorize BGR to access your Account Information maintained by identified third parties, on your behalf as your agent. When you use the “Add Accounts” feature of the Services, you will be directly connected to the website for the third party you have identified. BGR will submit information including usernames and passwords that you provide to log into the Site. You hereby authorize and permit BGR to use and store information submitted by you to accomplish the foregoing and to configure the Services so that it is compatible with the third party sites for which you submit your information. For purposes of this Agreement and solely to provide the Account Information to you as part of the Service, you grant BGR a limited power of attorney, and appoint BGR or BGR Bills as your attorney-in-fact and agent, to access third party sites, retrieve and use your information with the full power and authority to do and perform each thing necessary in connection with such activities, as you could do in person. YOU ACKNOWLEDGE AND AGREE THAT WHEN BGR IS ACCESSING AND RETRIEVING ACCOUNT INFORMATION FROM THIRD PARTY SITES, BGR IS ACTING AS YOUR AGENT, AND NOT AS THE AGENT OF OR ON BEHALF OF THE THIRD PARTY THAT OPERATES THE THIRD PARTY SITE. You understand and agree that the Services are not sponsored or endorsed by any third parties accessible through the Services. BGR is not responsible for any payment processing errors or fees or other Services-related issues, including those issues that may arise from inaccurate account information.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>11. BGR’s Intellectual Property Rights</h5>
<p>The contents of the Services, including its “look and feel” (e.g., text, graphics, images, logos and button icons), photographs, editorial content, notices, software (including html-based computer programs) and other material are protected under both United States and other applicable copyright, trademark and other laws. The contents of the Services belong or are licensed to BGR orBGR Bills or its software or content suppliers. BGR grants you the right to view and use the Services subject to these terms. You may download or print a copy of information for the Services for your personal, internal and non-commercial use only. Any distribution, reprint or electronic reproduction of any content from the Services in whole or in part for any other purpose is expressly prohibited without our prior written consent. You agree not to use, nor permit any third party to use, the Site or the Services or content in a manner that violates any applicable law, regulation or this Agreement.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>12. Access and Interference</h5>
<p>You agree that you will not:</p>
<ul>
<li>Use any robot, spider, scraper, deep link or other similar automated data gathering or extraction tools, program, algorithm or methodology to access, acquire, copy or monitor the Services or</p>
<p>any portion of the Services, without BGR’s express written consent, which may be withheld in BGR’s sole discretion;</p>
</li>
<li>Use or attempt to use any engine, software, tool, agent, or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or sea
<p>rch the rvices, other than the search engines and search agents available through the Services and other than generally available third-party web browsers (such as Microsoft Explorer);</p>
</li>
<li>Post or transmit any file which contains viruses, worms, Trojan horses or any other contaminating or destructive features, or that otherwise interfere with the proper working of the Services;
<p>or</p>
</li>
<li>Attempt to decipher, decompile, disassemble, or reverse-engineer any of the software comprising or in any way making up a part of the Services.</li>
</ul>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>13. Rules for Posting</h5>
<p>As part of the Services, BGR may allow you to post content on bulletin boards, blogs and at various other publicly available locations on the Sites. These forums may be hosted by BGR or by one of our third party service providers on BGR’s behalf. You agree in posting content to follow certain rules.</p>
<ul>
<li>You are responsible for all content you submit, upload, post or store through the Services.</li>
<li>You are responsible for all materials ("Content") uploaded, posted or stored through your use of the Services. You grant BGR a worldwide, royalty-free, non-exclusive license to host and use any Content provided through your use of the Services. Archive your Content frequently. You are responsible for any lost or unrecoverable Content. You must provide all required and appropriate warnings, information and disclosures. BGR is not responsible for the Content or data you submit through the Services. By submitting content to us, you represent that you have all necessary rights and hereby grant us a perpetual, worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, modify, display, and perform all or any portion of the content in connection with Services and our business, including without limitation for promoting and redistributing part or all of the site (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each User a non-exclusive license to access your posted content through the Sites, and to use, reproduce, distribute, prepare derivative works of, display and perform such content as permitted through the functionality of the Services and under this Agreement.</li>
<li>You agree not to use, nor permit any third party to use, the Services to a) post or transmit any message which is libelous or defamatory, or which discloses private or personal matters concerning any person; b)post or transmit any message, data, image or program that is indecent, obscene, pornographic, harassing, threatening, abusive, hateful, racially or ethnically offensive; that encourages conduct that would be considered a criminal offense, give rise to civil liability or violate any law; or that is otherwise inappropriate; c)post or transmit any message, data, image or program that would violate the property rights of others, including unauthorized copyrighted text, images or programs, trade secrets or other confidential proprietary information, and trademarks or service marks used in an infringing fashion; or d) interfere with other Users’ use of the Service, including, without limitation, disrupting the normal flow of dialogue in an interactive area of the Sites, deleting or revising any content posted by another person or entity, or taking any action that imposes a disproportionate burden on the Service infrastructure or that negatively affects the availability of the Service to others.</li>
<li>Except where expressly permitted, you may not post or transmit charity requests; petitions for signatures; franchises, distributorship, sales representative agency arrangements, or other business opportunities (including offers of employment or contracting arrangements); club memberships; chain letters; or letters relating to pyramid schemes. You may not post or transmit any advertising, promotional materials or any other solicitation of other users to use goods or services except in those areas (e.g., a classified bulletin board) that are designated for such purpose.</li>
<li>You agree that any employment or other relationship you form or attempt to form with an employer, employee, or contractor whom you contact through areas of the Sites that may be designated for that purpose is between you and that employer, employee, or contractor alone, and not with us.</li>
<li>You may not copy or use personal identifying or business contact information about other Users without their permission. Unsolicited e-mails, mailings, telephone calls, or other communications to individuals or companies whose contact details you obtain through the Services are prohibited.</li>
<li>You agree that we may use any content, feedback, suggestions, or ideas you post in any way, including in future modifications of the Service, other products or services, advertising or marketing materials. You grant us a perpetual, worldwide, fully transferable, sublicensable, non-revocable, fully paid-up, royalty free license to use the content and feedback you provide to us in any way.</li>
<li>You acknowledge that BGR uses our third party service provider, Get Satisfaction, Inc. ("Get Satisfaction") to help us provide, host and operate the "Get Help" area of the Service. You agree that if you choose to participate in, or post content to, the "Get Help" area of the Service (located at the domain satisfaction.BGR.com), such as by posting a new topic, following a topic or replying to an existing topic, then you agree to also comply with Get Satisfaction's Terms of Use and Community Guidelines, in addition to the terms of this Agreement.</li>
</ul>
<p>The Services may include a community forum or other social features to exchange information with other users of the Services and the public. BGR does not support and is not responsible for the content in these community forums. Please use respect when you interact with other users. Do not reveal information that you do not want to make public. Users may post hypertext links to content of third parties for which BGR is not responsible.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>14. Social media sites</h5>
<p>BGR may provide experiences on social media platforms such as Facebook®, Twitter® and LinkedIn® that enable online sharing and collaboration among users who have registered to use them. Any content you post, such as pictures, information, opinions, or any Personal Information that you make available to other participants on these social platforms, is subject to the Terms of Use and Privacy Policies of those platforms. Please refer to those social media platforms to better understand your rights and obligations with regard to such content.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>15. Disclaimer of Representations and Warranties</h5>
<p>THE SITES, SERVICES, INFORMATION, DATA, FEATURES, AND ALL CONTENT AND ALL SERVICES AND PRODUCTS ASSOCIATED WITH THE SERVICESOR PROVIDED THROUGH THE SERVICES (WHETHER OR NOT SPONSORED) ARE PROVIDED TO YOU ON AN “AS-IS” AND “AS AVAILABLE” BASIS. BGR, ITS AFFILIATES, AND ITS THIRD PARTY PROVIDERS, LICENSORS, DISTRIBUTORS OR SUPPLIERS (COLLECTIVELY, "SUPPLIERS") MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE CONTENT OR OPERATION OF THE SITE OR OF THE SERVICES. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK.</p>
<p>NEITHER BGR OR ITS SUPPLIERS MAKE ANY REPRESENTATIONS, WARRANTIES OR GUARANTEES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, RELIABILITY OR COMPLETENESS OF THE CONTENT ON THE SITES OR OF THE SERVICES (WHETHER OR NOT SPONSORED), AND EXPRESSLY DISCLAIMS ANY WARRANTIES OF NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE. NEITHER BGR OR ITS SUPLIERS MAKE ANY REPRESENTATION, WARRANTY OR GUARANTEE THAT THE CONTENT THAT MAY BE AVAILABLE THROUGH THE SERVICES IS FREE OF INFECTION FROM ANY VIRUSES OR OTHER CODE OR COMPUTER PROGRAMMING ROUTINES THAT CONTAIN CONTAMINATING OR DESTRUCTIVE PROPERTIES OR THAT ARE INTENDED TO DAMAGE, SURREPTITOUSLY INTERCEPT OR EXPROPRIATE ANY SYSTEM, DATA OR PERSONAL INFORMATION.</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. IN SUCH STATES LIABILITY IS LIMITED TO THE EXTENT PERMITTED BY LAW. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS OF SECTIONS 15 AND 17 OF THIS PROVISION MAY NOT APPLY TO YOU.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>16. Not a Financial Planner, Broker or Tax Advisor</h5>
<p>NEITHER BGR NOR THE SERVICES ARE INTENDED TO PROVIDE LEGAL, TAX OR FINANCIAL ADVICE. BGR IS NOT A FINANCIAL PLANNER, BROKER OR TAX ADVISOR. The Service is intended only to assist you in your financial organization and decision-making and is broad in scope. Your personal financial situation is unique, and any information and advice obtained through the Service may not be appropriate for your situation. Accordingly, before making any final decisions or implementing any financial strategy, you should consider obtaining additional information and advice from your accountant or other financial advisers who are fully aware of your individual circumstances.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>17. Limitations on BGR’s Liability</h5>
<p>BGR SHALL IN NO EVENT BE RESPONSIBLE OR LIABLE TO YOU OR TO ANY THIRD PARTY, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, LIQUIDATED OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFIT, REVENUE OR BUSINESS, ARISING IN WHOLE OR IN PART FROM YOUR ACCESS TO THE SITES, YOUR USE OF THE SERVICES, THE SITES OR THIS AGREEMENT, EVEN IF BGR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT, BGR’S LIABILITY TO YOU FOR ANY CAUSE WHATEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO A MAXIMUM OF $500.00 (FIVE HUNDRED UNITED STATES DOLLARS).</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>18. Your Indemnification of BGR</h5>
<p>You shall defend, indemnify and hold harmless BGR and its officers, directors, shareholders, and employees, from and against all claims, suits, proceedings, losses, liabilities, and expenses, whether in tort, contract, or otherwise, that arise out of or relate, including but not limited to attorneys fees, in whole or in part arising out of or attributable to any breach of this Agreement or any activity by you in relation to the Sites or your use of the Services.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>19. Ending your relationship with BGR
</h5>
<p>This Agreement will continue to apply until terminated by either you or BGR as set out below. If you want to terminate your legal agreement with GR, you may do so as follows:</p>
<p>To close your account for the BGR Service, please use the directions below:</p>
<ul>
<li>Login to your BGR.com account.</li>
<li>Go to “Your Profile”.</li>
<li>Locate the “delete BGR account” option under “More Options”.</li>
<li>Type in “delete” where prompted.</li>
<li>Enter in the password for your BGR.com account.</li>
<li>Press “Yes”</li>
<li>Your account will be closed and your ability to log in deactivated immediately. Your BGR.com account data will be removed within 48 hours subject to and as explained in our Privacy Statement.</li>
</ul>
<p>Please contact BGR Bills Support via our support center at <a href="http://bills.BGR.nanorep.com" target="_blank">http://bills.BGR
	BGR.nanorep.com</a> for instructions on how to close your Bill Pay Services Account.</p>
<p>BGR may at any time, terminate its legal agreement with you and access to the Services:</p>
<p>a. if you have breached any provision of this Agreement (or have acted in a manner which clearly shows that you do not intend to, or are unable to comply with the provisions of this Agreement); b. if BGR in its sole discretion believes it is required to do so by law (for example, where the provision of the Service to you is, or becomes, unlawful); c. for any reason and at any time with or without notice to you; or d. immediately upon notice, to the e-mail address provided by you as part of your Registration Information.</p>
<p>You acknowledge and agree that BGR may immediately deactivate or delete your account and all related information and files in your account and/or prohibit any further access to all files and the Services by you. Further, you agree that BGR shall not be liable to you or any third party for any termination of your access to the Services.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>20. Modifications</h5>
<p>BGR reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Sites or Services with or without notice. BGR reserves the right to change the Services, including applicable fees, in our sole discretion and from time to time. In such event, if you are a paid user to the BGR Services and Bill Pay Services, BGR will provide notice to you. If you do not agree to the changes after receiving a notice of the change to the Services, you may stop using the Services. Your use of the Services, after you are notified of any change(s) will constitute your agreement to such change(s). You agree that BGR shall not be liable to you or to any third party for any modification, suspensions, or discontinuance of the Services.</p>
<p>BGR may modify this Agreement from time to time. Any and all changes to this Agreement may be provided to you by electronic means (i.e., via email or by posting the information on the Sites). In addition, the Agreement will always indicate the date it was last revised. You are deemed to accept and agree to be bound by any changes to the Agreement when you use the Services after those changes are posted.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>21. Governing Law and Forum for Disputes</h5>
<p>California state law governs this Agreement without regard to its conflicts of laws provisions.</p>
<p>ANY DISPUTE OR CLAIM RELATING IN ANY WAY TO THE SERVICES OR THESE TERMS OF USE WILL BE RESOLVED BY BINDING ARBITRATION, RATHER THAN IN COURT, except that you may assert claims in small claims court if your claims qualify. The Federal Arbitration Act governs the interpretation and enforcement of this provision; the arbitrator shall apply California law to all other matters. Notwithstanding anything to the contrary, any party to the arbitration may at any time seek injunctions or other forms of equitable relief from any court of competent jurisdiction. WE EACH AGREE THAT ANY AND ALL DISPUTES MUST BE BROUGHT IN THE PARTIES' INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. BY ENTERING INTO THIS AGREEMENT AND AGREEING TO ARBITRATION, YOU AGREE THAT YOU AND BGR ARE EACH WAIVING THE RIGHT TO FILE A LAWSUIT AND THE RIGHT TO A TRIAL BY JURY. IN ADDITION, YOU AGREE TO WAIVE THE RIGHT TO PARTICIPATE IN A CLASS ACTION OR LITIGATE ON A CLASS-WIDE BASIS. YOU AGREE THAT YOU HAVE EXPRESSLY AND KNOWINGLY WAIVED THESE RIGHTS.</p>
<p>To begin an arbitration proceeding, send a letter requesting arbitration and describing your claim to BGR Inc., in care of our registered agent Corporation Service Company, 2711 Centerville Road, Wilmington, DE 19808. Arbitration will be conducted by the American Arbitration Association (AAA) before a single AAA arbitrator under the AAA’s rules, which are available at <a href="http://www.adr.org">www.adr.org</a> or by calling 1-800-778-7879. Payment of all filing, administration and arbitrator fees and costs will be governed by the AAA's rules, but if you are unable to pay any of them, we will pay them for you. In addition, we will reimburse all such fees and costs for claims totaling less than $75,000 unless the arbitrator determines the claims are frivolous. Likewise, we will not seek its attorneys’ fees or costs in arbitration unless the arbitrator determines your claims or defenses are frivolous. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the county where you live or at another mutually agreed location. The decision of the arbitrator shall be final and not appealable, and judgment on the arbitration award may be entered in any court having jurisdiction thereof. This Section 21 shall survive expiration, termination or rescission of this Agreement.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>22. Allegations of Copyright and Trademark Infringements; Notification</h5>
<p>BGR respects the intellectual property rights of others and BGR asks that users of the Site and Services do the same. If you believe that your intellectual property is being used on the Site in a way that constitutes copyright infringement, please provide our Designated Agent (set forth below) the following information (as required by Section 512(c)(3) of the Digital Millennium Copyright Act):</p>
<ul>
<li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
<li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site.</li>
<li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material.</li>
<li>Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted.</li>
<li>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
<li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
</ul>
<p>The information specified above must be sent to BGR’s Designated Agent, whose contact information is as follows:</p>
<p>BGR BGR Bills, Inc.</p>
<p>Attention: DMCA Designated Agent</p>
<p>1234 The Drive</p>
<p>The Great State of, CA 93401</p>
<p>Fax: 555-555-1234</p>
<p>Email: <a href="mailto:care@bills.BGR.com">care@bills.BGR.com</a></p>
<p>Please note that Section 512(f) of the Digital Millennium Copyright Act may impose liability for damages on any person who knowingly sends meritless notices of infringement. Please do not make false claims.</p>
<p>Any information or correspondence that you provide to BGR Bill’s may be shared with third parties, including the person who provided BGR Bill’s with the allegedly infringing material.</p>
<p>Upon receipt of a bona fide infringement notification by the Designated Agent, it is BGR Bill’s policy to remove or disable access to the infringing material, notify the user that it has removed or disabled access to the material, and, for repeat offenders, to terminate such user's access to the service.</p>
<p>If you believe that your content should not have been removed for alleged copyright infringement, you may send BGR Bill’s Designated Agent a written counter-notice with the following information:</p>
<ul>
<li>Identification of the copyrighted work that was removed, and the location on the Site where it would have been found prior to its removal;</li>
<li>A statement, under penalty of perjury, that you have a good faith belief that the content was removed as a result of a mistake or misidentification; and</li>
<li>Your physical or electronic signature, together with your contact information (address, telephone number and, if available, email address).</li>
</ul>
<p>If a counter-notice is received by the Designated Agent, we may send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed material or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the user, the removed material may be replaced or access to it restored in 10 to 14 business days or more after receipt of the counter-notice, at our discretion.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>II. SUPPLEMENTAL TERMS AND CONDITIONS FOR THE SERVICES.</h5>
<p>These Supplemental Terms and Conditions apply for the, BGR Quickview, Credit Score and Bill Pay Services and shall prevail over any conflict or inconsistency with the Agreement above. Capitalized terms not otherwise defined below have the meanings provided in the General Terms above.</p>
<h5>23. BGR QuickView.</h5>
<p>You can download from the Mac App Store BGR QuickView, a companion app to the BGR Service, and upon payment of the applicable fee BGR QuickView will give you an up-to-date snapshot of your finances by performing the some of the following: (i) Know when you have a new transaction or account alert; (ii) Quick access to your financial information; and (iii) Syncs with the Service on the web and mobile. You are responsible for the fee you incur and are charged by a third party (i.e, Apple), which may change from time to time, in connection with your download and use of BGR QuickView. BGR has no obligation to refund any payments made to such third party for your use of BGR QuickView as set out in this Agreement.</p>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>24. Credit Score Services.</h5>
<p>BGR may provide you with the free credit score, report summary and monitoring alerts (“Credit Score Service”) and a paid version BGR Credit Monitoring available to BGR customers, when you register for the BGR Services (“collectively the “Credit Score Services”). The BGR Credit Monitoring shall be subject to and governed by the terms of this Agreement and the supplemental terms and conditions available when you sign up for the BGR Credit Monitoring service. The Credit Score Services are available on the Quicken Services mobile App. The Credit Score Services may provide you with information about your credit profile including your credit report summary, credit score, monitoring or alert services and interactive tools where available. Credit Score Services will be provided via our website, including via mobile applications, where available. Some Credit Score Services will be provided through our third party processing agent, Equifax Information Services, LLC (“Processing Agent”). You may select from two types of Credit Score Services, with features described below.</p>
<ol type="A">
<li>
<p><span class="underline">BGR Free Credit Score Services</span>. The BGR Free Credit Score Services is a free version of the BGR Services available to BGR customers. This BGR Free Credit Score Services includes the following:</p>
<ul>
<li>Single-bureau credit score with periodic updates and tracking as described on the website. The credit score provided to you is an Equifax® credit score, based on a proprietary credit model developed by Equifax which may use information in your Equifax, Experian and TransUnion credit files.</li>
<li>Potential key factors affecting your credit score, credit score comparison to national norms and simulators/ credit score calculator to understand how specific actions might affect your credit scores.
<p>Suggestions, tips and educational materials and information about other products and services that might be of interest to you.</p>
</li>
</ul>
</li>
<li><span class="underline">Additional Credit Products</span>. Additional credit products may be made available to you via BGR.com Site and may include products from third parties such as our Processing Agent. Please review the specific features, terms and conditions and associated fees before you purchase.
<p>BGR does not guarantee that you will receive your free credit report information via the BGR Services. You must satisfy our eligibility requirements. You may obtain your own report without the use of the BGR Services. You have the right to a free credit report from AnnualCreditReport.com or (877) 322-8228, the ONLY authorized source under Federal law.</p>
<p> </p>
</li>
<li><span class="underline">Authorization for Credit Score Services</span>. You must be at least 18 years of age to use these Credit Score Services, and you must be the subject of the credit report that you are seeking. You hereby authorize BGR to do all of the following in connection with providing you the Credit Score Services: (i) verify your identity and share with our Processing Agent certain non-public personal information about You, including Your Social Security Number; (ii) request and obtain your consumer credit report, including your score from our Processing Agent throughout the term in which we provide you the Credit Score Services; such request constitutes "written instructions" in accordance with the Fair Credit Reporting Act (“FCRA”); and (iii) use and retain your credit information, along with the other information you have given us access to under the Agreement, to provide the Services and use with other BGR services that include substantially similar functionalities as these Credit Score Services. <strong>You agree that we may use and analyze your information as follows: (a) present you an overview of your credit profile including detailed information where available; (b) provide you with customized recommendations and general information about you; and (c) serve you targeted ads and other communication based on your information.</strong> BGR may send you information via email, text or online display or other means of delivery in BGR’s reasonable sole discretion. <strong>We may also aggregate and evaluate your information to do statistical analysis to provide historical or comparative information and to improve BGR products and services.</strong> We will obtain your prior consent if we use your identifying information for any other purpose not expressly permitted under these Terms. Please refer to our <a href="/privacy">Privacy Statement</a> for more information.</li>
<li><span class="underline">Restrictions</span>. You agree to provide true, accurate and current information. It is a violation of federal criminal laws to knowingly or willfully obtain information from a consumer reporting agency under false pretenses. You agree not to do any of the following: (i) violate any applicable local, state, national or international law, or any regulations having the force of law; (ii) further or promote any criminal activity or enterprise or provide instructional information about illegal activities; or (iii) obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Credit Score Services.</li>
<li><span class="underline">Term, Cancellation and Refund Policy</span>. BBGR may terminate the Services for any reason at any time. If you purchase another credit products via our website, please review any additional terms where applicable.</li>
<li><span class="underline">Customer Support</span>. Customer support will vary depending on the Services. Please refer to the Services website for information. For questions regarding your credit score or credit report, please contact the Processing Agent directly at 1-866-373-7830. YOU UNDERSTAND AND AGREE THAT THE SERVICES DO NOT INCLUDE THE PLACING OF FRAUD ALERTS WITH ANY CONSUMER REPORTING AGENCIES. YOU MUST CONTACT THE CONSUMER REPORTING AGENCIES DIRECTLY IF YOU SUSPECT ANY FRAUD ACTIVITY.</li>
<li><strong><span class="underline">BGR Is Not a Credit Repair Company, Credit Reporting Agency, Broker Or Advisor</span></strong><br />
<ol type="i">
<li><strong>You acknowledge that BGR is not a credit repair company or similarly regulated organization under applicable laws, and does not provide credit repair services.</strong> Where available, information provided via the Services is for your educational and reference purpose only and is provided at no additional charge. The Services are intended to provide you with general information and is not intended to provide, legal, tax or financial advice. We do not provide any services to repair or improve your credit profile or credit score, nor do we provide any representation that the information we provide will actually repair or improve your profile. Consult the services of a competent licensed professional when you need any type of this assistance.</li>
<li>You acknowledge that BGR is not a "consumer reporting agency" as that term is defined in the Fair Credit Reporting Act as amended.</li>
</ol>
</li>
<li>
<p><span class="underline">Product Notices</span></p>
<ol type="I">
<li>The credit scores provided under the Services use the Equifax Credit Score™, which is a proprietary credit model developed by our Processing Agent. The credit score is intended for your own educational use. It is also commercially available to third parties along with numerous other credit scores and models in the marketplace. Please keep in mind third parties are likely to use a different score when evaluating your creditworthiness. Third parties will take into consideration items other than your credit score or information found in your credit file, such as your income.</li>
<li>Results from credit score calculator or simulator are provided for educational purposes only and are intended to show the impact that certain hypothetical actions could have on your credit score, assuming all other variables remain constant. The results are not a guarantee. Your actual score calculation may vary as information in your credit profile may change.</li>
</ol>
</li>
</ol>
<h5>25. Bill Payment Service</h5>
<ol type="A">
<li><span class="underline">Description and Fees of Bill Payment Service</span>. BGR Bills provides a bill payment service that allows you to make payments to certain third parties. To be eligible to use the Bill Payment Service, you must be a resident of the United States or one of the countries specified by BGR Bills. In order to use the Bill Payment Service, you will need to provide BGR Bills with your account information with service providers you choose (such as account passwords and usernames) and any information necessary for us to access your accounts with such service providers ("Bill Payment Account Information"). By using the Bill Payment Service, you expressly authorize BGR Bills to access the Bill Payment Account Information, on your behalf and as your agent, solely for the purpose of providing the Bill Payment Service to you. Each time you add an account through your use of the Bill Payment Service, you will be directly connected to the website for the third party you have identified. Once you have added an account through your use of the Bill Payment Service, BGR Bills will submit information, including usernames and passwords that you provide, to log you into the third party site (each, a "Third Party Site"). You hereby authorize and permit BGR Bills to use and store your Bill Payment Account Information to accomplish the foregoing and to configure the Bill Payment Service so that they are compatible with the Third Party Sites for which you submit your Bill Payment Account Information.</li>
<li><span class="underline">Description of Fees</span>. Any fees applicable to your use of a Bill Payment Service will be charged regardless of whether or how often you use the Bill Payment Service during each period for which you have subscribed to the applicable Bill Payment Service. There may be charges for additional transactions and other optional services that you elect to use. You agree to pay fees for the all Bill Payment Service you use or subscribe to as described on the Sites.</li>
<li><span class="underline">Payee Information; Authority</span>. By initiating a payment through the Bill Payment Service, you authorize BGR Bills to charge the account that you designate as the account to which the bill payments should be charged or withdrawn from (the "Funding Account"). You agree to maintain a balance or available credit limit in the specified Funding Account that is sufficient to fund all payments you initiate. You represent and warrant that you have the right to authorize BGR Bills to charge the Funding Account for payments you initiate using the Bill Payment Service. You will indemnify and hold BGR harmless from any claims by any other owner of the account
<p>You are responsible for confirming the accuracy of the information you provide about each payment you send, including the email address or telephone number of the recipient (the "Payee"), and the amount of the transaction.</p>
<p>You represent and warrant that BGR Bills may send communication to the Payee on your behalf in connection with the Bill Payment Service. By using the Bill Pay Service, you represent and warrant that you and each person you identify have consented to receive ongoing communication, including text messages from us. Such communication may include messages, including text messages, to the recipient of the Bill Payment Service to receive money you had paid them using the Bill Payment Service. You agree to inform BGR Bills if a person withdraws his consent to receiving text messages from you.</p>
<p>BGR Bills does not charge a fee to send a text message when using the Bill Pay Service. However, any text messages sent and/or received are subject to standard text message rates depending on the recipient’s carrier and terms and conditions with the carrier. To stop receiving messages, reply STOP to any text messages you receive from us.</p>
</li>
<li>
<p><span class="underline">Limits On Payees, Payment Amounts And Methods</span>. You acknowledge that certain Payees may not accept payment from all types of funding sources and that we may otherwise limit the payment methods available for a particular Payee. For example, you may not be permitted to use a credit card to make a mortgage payment. Additionally, BGR Bills may, at its discretion, impose limits on the number and amount of payments, in aggregate, that you can send using the Bill Payment Service.</p>
<p>BGR Bills may refuse to permit payment to any Payee if we reasonably believe such refusal is necessary or advisable for legal or security reasons. If you fail to maintain a balance in the applicable Funding Account that is insufficient to fund any payment that you initiate, BGR Bills may refuse to make any subsequent payment for as long as we determine to be necessary or appropriate. BGR Bills also reserve the right to refuse to make any other payment.</p>
<p>BGR Bills will make payments you request through the Bill Payment Service either electronically, by charging your designated credit card or via other form of funds transfer that BGR Bills may choose to employ. Payments to Payees outside of the United States or its territories are prohibited through the Bill Payment Service. The Bill Payment Service does not support payment to all types of billers, including certain government agencies and bills such as tax payments and court-ordered payments.</p>
</li>
<li><span class="underline">Rejected Payments</span>. When you send a payment via the Bill Payment Service, the Payee is not required to accept it. You agree that you will not hold BGR Bills liable for any damages resulting from a Payee not receiving payment made through the Bill Payment Service for any reason. If payment is not accepted for any reason, BGR Bills will void the payment and credit the applicable Funding Account.</li>
<li>
<p><span class="underline">Inability to Access Funds from Funding Account</span>. In using the Bill Payment Services, you are requesting BGR Bills to facilitate making payments from your Funding Account(s) to your Payee(s). If Bill Payment Service is unable to access funds from your specified Funding Account to complete a bill payment transaction you request for any reason (for example, non-sufficient funds, closed account, inability to locate account, or reversal by you and/or your bank), the transaction may not be completed. If Bill Payment Service is unable to access funds from your specified Funding Account for any reason, you agree that:</p>
<ul>
<li>you will reimburse BGR Bills immediately, upon demand, the transaction amount to the extent that BGR Bills sent a payment to the Payee on your behalf;</li>
<li>you will reimburse BGR Bills for any fees imposed on us as a result of the transaction; and</li>
<li>you will reimburse the Bill Payment Services for any fees, including reasonable attorney fees, we incur in attempting to collect the amount of the transaction from you.</li>
</ul>
<p>Additionally, you agree that BGR Bills may: (a) reverse any corresponding credit or direct deposits issued to you; (b) reverse any payments BGR Bills made to your Payee; (c) apply any money currently held by BGR Bills to any amount owed to us; (d) initiate electronic fund transfer from your account to collect any unpaid amounts and our fees.</p>
<p>BGR Bills is not responsible for any overdraft fees, over-the-limit fees, or insufficient fund charges (including finance charges, late fees, or similar charges) that result from your failure to maintain a balance or available credit in the Funding Account that is sufficient to fund all payments you initiate.</p>
<p>If BGR Bills is not able to recover all amounts owed to us, we may report this information to third parties, including consumer reporting agencies, financial institutions. BGR Bills reserves all rights to pursue all available legal remedies to recover all owed amounts.</p>
<p>Any fees applicable to your use of the Bill Payment Services will be charged regardless of whether or not or how often you use the Bill Payment Services during each period for which you have subscribed to the applicable Service. There may be charges for additional transactions and other optional services that you elect to use. You agree to pay fees for the all Bill Payment Services you use or subscribe to as described on the Sites.</p>
</li>
<li>
<p><span class="underline">Your Liability</span>. You are solely liable for errors you make in using the Bill Payment Service, including the following:</p>
<ul>
<li>you direct BGR Bills to submit a payment to a Payee from the wrong Funding Account;</li>
<li>you erroneously direct BGR Bills to submit a payment to a Payee multiple times;</li>
<li>you direct BGR Bills to submit the wrong amount to a Payee;</li>
<li>you direct BGR Bills to submit a payment to the wrong Payee; or</li>
<li>you change your mind about making a payment to a Payee after directing BGR Bills to submit the payment.</li>
</ul>
<p>You are responsible for all fees, fines, penalties, and other liability incurred by BGR Bills, a Payee, you or a third party caused by or arising out of your breach of this Agreement and/or your use of the Bill Payment Service. You agree to reimburse BGR Bills, a Payee or the applicable third party for any and all such liability.</p>
<p>In the event that you are liable for any amounts owed to BGR Bills for a payment you authorized through the Bill Payment Service, BGR Bills may immediately remove such amounts from or charge such amounts to your applicable Funding Account. If the applicable Funding Account does not have funds or available credit sufficient to cover your liability, you will be required to immediately add funds to the Funding Account or otherwise provide payment to BGR Bills through other means. If you do not do so, BGR Bills may engage in collection efforts to recover such amounts from you.</p>
<p>BGR Bills does not have control of, or liability for, the products or services that are paid for via the Bill Payment Service.</p>
</li>
<li>
<p><span class="underline">Delays, Unauthorized Transactions, or Errors</span></p>
<ol type="i">
<li>
<p><strong>Payment Processing Delays and Protection for Late Fees.</strong> You acknowledge that some transactions may take longer to be credited to your account with the applicable Payee due to circumstances beyond BGR Bills' control, such as delays in handling and posting payments by Payees or financial institutions or errors with account information or funding instructions.</p>
<p>When you send a payment to certain Payees, the payment may be treated as an authorization to the Payee to process your payment and complete the transaction. Some Payees may delay processing your payment, in which case the payment may be held as pending until the Payee processes your payment and your payment authorization will remain valid for up to 30 days.</p>
<p>To help ensure that there is enough time for the applicable Payee to receive any payments you submit through the Bill Payment Service, you should submit payment instructions at least 6 business days prior to the due date for the applicable bill. If the due date falls on a weekend or holiday, you must submit the payment sufficiently in advance to include an additional day for processing. It is solely your responsibility to submit payments so they arrive by the Payee's due date.</p>
<p>Subject to the other provisions of this Agreement, BGR Bills will bear responsibility for any satisfactorily documented late payment related charges up to a reasonable amount, not to exceed $50.00 in the event a payment posts after its due date provided that the payment was submitted by you for payment in accordance with the guidelines specified in the beginning of this paragraph and the Bill Payment Service issued you a confirmation number for a payment, unless we are not responsible to you for one of the reasons listed in this section or below under "Protection for BGR Bills Errors." THIS IS BGR BILLS ONLY OBLIGATION TO YOU FOR ANY PAYMENT ERRORS, DELAYS, OR FAILURE. IF YOU DO NOT FOLLOW THESE RULES OR IF YOU DO NOT ALLOW ENOUGH TIME TO COMPLETE A PAYMENT, YOU ALONE ARE RESPONSIBLE FOR ANY PENALTIES OR LATE CHARGES ON THAT PAYMENT.</p>
<p>Any fees applicable to your use of a Service will be charged regardless of whether or how often you use the Services during each period for which you have subscribed to the applicable Service. There may be charges for additional transactions and other optional services that you elect to use. You agree to pay fees for the all Services you use or subscribe to as described on the Sites.</p>
</li>
<li>
<p><strong>Errors or other Issues Regarding Payments.</strong> It is your responsibility to review all payment transactions initiated in the Bill Payment Service against account statements you receive from your bank or other financial institution. Your payment transaction information is included in the receipts we provide you. ALL QUESTIONS ABOUT TRANSACTIONS MADE THROUGH THE BILL PAYMENT SERVICE MUST BE DIRECTED TO BGR BILLS, AND NOT TO THE BANK OR OTHER FINANCIAL INSTITUTION WHERE YOU HAVE YOUR ACCOUNT. We will work with you and your biller (as appropriate) to resolve errors that we caused.</p>
<p>We may not send you a periodic statement listing transactions that you make using the Bill Payment Service. The transactions will appear only on the statement issued by your bank or other financial institution.</p>
<p>IF YOUR CREDENTIALS TO ACCESS THE BILL PAYMENT SERVICES OR YOUR MOBILE DEVICE ARE LOST OR STOLEN, NOTIFY US AT ONCE USING THE CONTACT METHODS SPECIFIED IN SECTION 6 OF ARTICLE I (GENERAL TERMS) ABOVE.</p>
</li>
<li>
<p><strong>Protection for BGR Bills Errors.</strong> BGR Bills will use commercially reasonable efforts to facilitate the payment of your bills in accordance with this Agreement. However, BGR Bills will not be liable, for instance:</p>
<ul>
<li>if, through no fault of ours, you do not have enough money in your account to make the transfer;</li>
<li>the payment is rejected, returned, mishandled, or delayed by the Payee for any reason;</li>
<li>you have provided BGR
 Bills with incorrect information about the Payee;</li>
<li>the Funding Account you specify as the payment source is closed or does not contain sufficient funds to complete the payment or the charge is rejected or returned by your bank or financial institution;</li>
<li>due to any pre-announced unavailability of the Bill Payment Service;</li>
<li>due to fraud or attacks on our systems, service or the Bill Payment Service;</li>
<li>due to third party service providers; or</li>
<li>due to circumstances beyond our control (for example, fire, flood, interference from an outside source, postal delays, or any failure by your computer, software, or Internet connection).</li>
</ul>
</li>
<li>
<p><strong>Unauthorized Transactions.</strong> You must notify BGR Bills immediately if you suspect or believe that a transaction has occurred through the Bill Payment Service that you did not authorize or that you believe an incorrect amount was authorized. You may contact us using the contact methods specified in section 5 of Article I (General Terms) above. If you initially provide information to us via the telephone, we may require that you send your complaint or question in writing. You will be asked and are required to provide us with the following information: your name; the email address registered for the Bill Payment Service account; a description (including dollar amount) of the transaction that you believe is unauthorized or in error; and a BGR Bills reference/transaction ID; and explanation to why you believe there was unauthorized transaction or error. If we decide that there was no error, we will send you an explanation. You may ask for copies of the documents that we used in our investigation.</p>
<p>For unauthorized transfers and errors with respect to your credit card or debit card that are not related to the Bill Payment Service, please see your applicable card holder agreement.</p>
</li>
</ol>
</li>
<li>
<p><span class="underline">Risk Monitoring; Unusual or Suspicious Transactions</span>. In an effort to manage our risk, we may monitor your transactions and processing activity for high-risk practices or for fraudulent transactions. We may also engage third-party service providers to assist in these efforts and other elements of the Bill Payment Service. If BGR Bills believes there is suspicious or unusual activity, BGR
BGR Bills may temporarily suspend your access to Bill Payment Service. Suspicious or unusual activity includes, but is not limited to changes in your average transaction amount or processing pattern or use of different payment accounts. BGR Bills may require additional documentation to promptly reinstate your access to the Bill Payment Service.</p>
</li>
<li>
<p><span class="underline">Termination</span>. BGR Bills may terminate or suspend your access to the Bill Payment Service at any time. Neither termination nor suspension shall affect your liability or obligations under this Agreement. In the event you or BGR Bills terminates your account, any payment(s) BGR Bills has already processed before the requested termination date may be completed. You should verify payment directly with your intended payee. BGR Bills is not responsible for any payments not completed by us as a result of termination.</p>
</li>
</ol>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<h5>26. Bill Processing Services</h5>
<ol type="A">
<li><span class="underline">Description of Service; Disclaimer</span>. BGR Bills will provide a bill processing service for merchants and other billers (each a "Biller") that engage BGR Bills to process certain payments they receive from their payers ("Payers") who are also BGR Bills users. BGR Bills is not a party to these payments or to their underlying commercial transactions, and BGR Bills disclaims any and all responsibility for any payments or other disputes between Billers and Payers. Such disputes are entirely between the Billers and their Payers. BGR Bills is the payment processor for the Billers.</li>
<li><span class="underline">Registration</span>. Each Biller must register with BGR Bills and accept this Agreement. BGR Bills will collect information from Billers to enable us to verify your identities and satisfy ourselves that it is appropriate for BGR Bills to process your payment transactions in accordance with our legal obligations under such laws as "know your customer" and OFAC. BGR Bills reserves the right to decline to accept a Biller into our Biller Processing Service, or to suspend or terminate our processing for any Biller at any time, or to suspend or terminate our Biller Processing Service entirely at any time and at our sole discretion.</li>
<li><span class="underline">Additional Agreements</span>. If required by an automated clearing house association (ACH), another processor or one of our banks, a Biller may have to enter into additional agreements. If you are unwilling to do so if requested, we may suspend or terminate your access to our Biller Processing Service.</li>
<li><span class="underline">Bill Processing Method</span>. BGR Bills will process payments for Billers by (i) facilitating ACH debit entries or other methods to withdraw funds from our users' funding accounts, (ii) receiving these funds on your behalf, (iii) deducting our bill payment processing fee; and (iv) remitting the balance to you. You hereby authorize BGR Bills to process bill payments for you in accordance with our Terms of Use and to make payments to you by paper draft or electronic funds transfer as long as you are a participant in our Biller Processing Service.</li>
<li><span class="underline">Termination by You</span>. You may at any time instruct us to discontinue our Biller Processing Service for you by logging into your processor account and following the instructions provided. Your instructions will become effective in five (5) business days or such longer period as shall be commercially reasonable under the circumstances for us, our processors and banks to act on your instructions.</li>
<li><span class="underline">Payments Received on Your Behalf; Release of Payer</span>. Payments under this program will be originated by any one of your Payers (our users) directing us, as your bill payment processor, to facilitate the withdrawal of funds from a Payer account to satisfy a bill payment or other debt the Payer owes to you. When BGR Bills, as your bill payment processor, receive a payment from a Payer on your behalf, you expressly agree that you have received that payment from the Payer, and as of that time, you fully release that Payer from any obligation the Payer had to you for payment in that amount. You agree that you will not thereafter attempt to collect on such obligation and will treat it as conclusively discharged.</li>
<li><span class="underline">Certain Limitations on Transactions</span>. BGR Bills provide our Biller Processing Service only for U.S. dollar payments made from Payers in the United States to Billers located in the United States who are engaged solely in lawful activities. Payments must be for goods sold or services rendered by the Biller. You hereby represent that you understand and meet all the criteria in this section.</li>
<li><span class="underline">Our Rights in Cases of Fraud or Unlawful Activities</span>. If we believe a requested payment to you may have arisen from fraud or unlawful activity or that its completion may harm us or any of our users, processors or banks, we may refuse to process that transaction or, if processed, refuse to remit such funds to you. If such a transaction has already been remitted to you, you authorize us to debit the transaction amount from your bank account within 90 days of the date the transaction was initiated. You expressly authorize us to share with law enforcement agencies any information relating to your business or our transactions with you. We may ask you for additional information about your business and transactions with us at any time, and you agree to provide it.</li>
<li><span class="underline">Settlement</span>. In the normal course, we will endeavor to make an electronic funds transfer to a designated bank account of yours within two to four business days after we receive payment on your behalf from one of your Payers. We may, at our sole discretion, accelerate these payments to you, but we also reserve the right to delay or withhold payments to you in accordance with the provisions of our Terms of Use.</li>
<li><span class="underline">Transaction Confirmation and Error Reporting</span>. When we make a payment to you, we will post a payment confirmation that you can view securely on our website. You are responsible for regularly monitoring information regarding the transactions we process for you. Except as may otherwise be provided by law, you are responsible for compiling, reconciling and retaining such information. If you believe there is an error in a transaction we have posted or that you have not received confirmation of a payment, you agree to bring this to our attention in writing through our website immediately.</li>
<li><span class="underline">Correction of Errors</span>. We will attempt to rectify processing errors we discover. If we determine we have paid you less than you were entitled to receive, we will send you an appropriate amount. If an error has resulted in your receiving more than you were entitled to, you agree to promptly refund the excess. You agree that we may set off any amount you owe us from future payments due to you. Failure to properly notify us within 60 days of an error first appearing in a payment confirmation we have made available to you will be deemed a waiver of any rights you may have regarding such error.</li>
</ol>
<p><a class="toc" href="/terms/#toc">Back to Top</a></p>
<p><strong>27. Apple Requirements.</strong> If you downloaded any of the Services or product from the Mac App Store, the following terms also apply to you:</p>
<ol type="A">
<li><strong>Acknowledgement</strong>: You acknowledge that this Agreement is between you and BGR only, and not with Apple, and BGR, not Apple, is solely responsible for the Software and the content thereof.</li>
<li><strong>Scope of License</strong>: The license granted to you for the Software is a limited, non-transferable license to use the Software on Mac product that you own or control and as permitted by the Usage Rules set forth in the terms of service applicable to the Mac App Store.</li>
<li><strong>Maintenance and Support</strong>: BGR and not Apple is solely responsible for providing any maintenance and support services, for which additional fees may apply, with respect to the Services. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Software.</li>
<li><strong>Warranty</strong>: BGR is solely responsible for any product warranties, whether express or implied by law, to the extent not effectively disclaimed. In the event of any failure of the Software to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the Software to you. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the Software, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be BGR’s sole responsibility.</li>
<li><strong>Product Claims</strong>: BGR, not Apple, is responsible for addressing any user or third party claims relating to the Software or the user’s possession and/or use of the Software, including, but not limited to: (i) product liability claims; (ii) any claim that the Software fail to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</li>
<li><strong>Intellectual Property Rights</strong>: You acknowledge that, in the event of any third party claim that the Software or your possession and use of the Software infringes that third party’s intellectual property rights, BGR, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim.</li>
<li><strong>Legal Compliance</strong>: You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a terrorist-supporting country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.</li>
<li><strong>Developer Contact Info</strong>: Direct any questions, complaints or claims to: BGR Inc, The One Way, The Great State of, CA 93401 or <a href="https://www.BGR.blah/help/" target="_blank">https://www.BGR.blah/help/</a></li>
<li><strong>Third Party Terms of Agreement</strong>: You must comply with any applicable third party terms of agreement when using the Software.</li>
<li><strong>Third Party Beneficiary</strong>: You acknowledge and agree that Apple and Apple’s subsidiaries are third party beneficiaries of this Agreement, and that, upon your acceptance of the terms and conditions of the Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce the Agreement against you as a third party beneficiary thereof.</li>
</ol>